name: Music Website
url: https://tumpnt.github.io/music-website/
repository: tumpnt/music-website

permalink: pretty
production: true

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false

exclude:
  - lib
  - Gemfile
  - Gemfile.lock
  - bower.json
  - README.md
  - gulffile.js
  - vendor
  - ".gitignore"
  - CNAME
  - icomoon-selection.json

defaults:
- scope:
    path: ""
  values:
    image: /favicon.ico