name: Music Website
url: https://tumpnt.github.io/music-website/
repository: tumpnt/music-website

permalink: pretty
production: true

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false

exclude:
  - README.md
  - ".gitignore"

defaults:
- scope:
    path: ""
  values:
    image: /favicon.ico